[bridge_phone_sites]
rpi-site-4 ansible_host=10.8.0.40 ansible_user=root
# Add more sites here as you add them:
# rpi-site-5 ansible_host=10.8.1.2 ansible_user=root

[bridge_phone_sites:vars]
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
